// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkXI8paSngl8m1FzlNRpz06KTFDxINSBM',
    appId: '1:192044922552:web:021444b428f85e37fb664d',
    messagingSenderId: '192044922552',
    projectId: 'chat-81be7',
    authDomain: 'chat-81be7.firebaseapp.com',
    storageBucket: 'chat-81be7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh8PoKY6yDchLw5McWqPMw8B8O9ymO2YA',
    appId: '1:192044922552:android:dae134a75778bde5fb664d',
    messagingSenderId: '192044922552',
    projectId: 'chat-81be7',
    storageBucket: 'chat-81be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImfg3PO-baTk1szyqoqiXF1XMPlQ7gC8',
    appId: '1:192044922552:ios:a7a2f8b03db76c5efb664d',
    messagingSenderId: '192044922552',
    projectId: 'chat-81be7',
    storageBucket: 'chat-81be7.appspot.com',
    iosClientId: '192044922552-058u8e859bd4s3raaj9nho6bac81unc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCImfg3PO-baTk1szyqoqiXF1XMPlQ7gC8',
    appId: '1:192044922552:ios:a7a2f8b03db76c5efb664d',
    messagingSenderId: '192044922552',
    projectId: 'chat-81be7',
    storageBucket: 'chat-81be7.appspot.com',
    iosClientId: '192044922552-058u8e859bd4s3raaj9nho6bac81unc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
